POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "kfir",
    "password": "123"
}

###

GET http://localhost:3000/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtmaXIiLCJzdWIiOjEsImlhdCI6MTYyNjQzMTg0NywiZXhwIjoxNjI2NDMyMTQ3fQ.3OqsHGZHUjzOiqPdAc_C9dTtPzu_Pik59MaLsxPP-6g

###

GET http://localhost:3000/auth/refresh HTTP/1.1
Cookie: refreshToken=s%3AeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtmaXIiLCJzdWIiOjEsImlhdCI6MTYyNjQzMTUyMywiZXhwIjoxNjI5MDIzNTIzfQ.r5OSAr0QeR4M2JsXrvBm-6jMRIWlFXfxY3rdMWKZoTs.ZIa9rSFPUyOzJn%2BfXGx9HpBDs2WurP%2BXY7OdEfWGdog
