import Head from "next/head";
import Home from "../components/home.component";

export default function HomePage() {

  return (
    <div>
      <Head>
        <title>MyWay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />

      
    </div>
  );
}
