import type { AppProps } from "next/app";
import Layout from "../components/layout/layout.component";
import { SWRConfig } from "swr";
import axios from "axios";
import Head from "next/head";
import 'tailwindcss/tailwind.css'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <SWRConfig
      value={{
        fetcher: (resource) =>
          axios.get(resource).then((res) => res?.data || null),
      }}
    >
      <Head>
        <title>MyWay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        {/* <script
          src="https://kit.fontawesome.com/2f4ab785b9.js"
          crossOrigin="anonymous"
        ></script> */}
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </SWRConfig>
  );
}
export default MyApp;
